{% set version = "2.8.0" %}

package:
  name: pyathena
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyAthena/PyAthena-{{ version }}.tar.gz
  sha256: 0f103ed95474aa15a9f81315cf8b095fb91d0cd7b711feafc01d8414116ed271

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - setuptools
    - boto3 >=1.4.4
    - botocore >=1.5.52
    - sqlalchemy
    - tenacity >=4.1.0

test:
  imports:
    - pyathena

about:
  home: https://github.com/laughingman7743/PyAthena/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python DB API 2.0 (PEP 249) compliant client for Amazon Athena
  dev_url: https://github.com/laughingman7743/PyAthena/

extra:
  recipe-maintainers:
    - JorgeGarciaIrazabal
    - mariusvniekerk
