travis:
  secure:
    BINSTAR_TOKEN: uAQGPfe4OQamI6Q4al/Lmrq8oXg4X9N9FaL7K32zZrCZIU3HyKsbl7VgDcKak1UYcC2VMsL5pzNYFUMBTx70VuxSQDk715yBvFNzoHsmmIqLMbF0+ISu8Ftm2EBDdcsbV2r6b6rhTDRF13TD7kg4XeqSG4le7lcs0+dw/gRhh+zLV5ITcDPwhSIHnmV0XMErZEdO0f/R0oIUubD7Yn0g5NCY0H39nS4HBLOY8CONqOraqC3hJ2ZVxo+pV2dmu7USeatBKzlqq0K0QOfqryR63/QcpHcUo/Y8MLdjNbfTpHkSTh2m47PQsReZqmkO2Ge5XWvOew+fd2WuucFFgFO7ZGp5fFATX3/sEhBqadiOjnYY1+Ra1lDWfIZiuVc4z+E7Hg8y9/Yhm4tsbnENDYZiPXQ+xRlkJVspc64yZtgBX2wFhxyVjQKoYXpcGcLK4s8jtcJnocq0KiWM/UtDDr5hpRoVApXXqbtJBae0Sc1DsA1yy4/w2l7RDpfbRzDMSLI3l1iZjEPARuuCGFiGPt60lccaUwjEB39rTmSWOuf1IveZSd8HREQbHBKfbwMx5d9RJwM1dnOZCN1IrzZDhpaPX5PYWeSFyOC+HPq5+9ZCSSyJt5XJ3ov9P2hwYWAhGjWBcUd1Uyrvzy7itCI5O3lwDjfgoQPVO8f2aYlw88lrFOo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
